# Frameworks checked against Redis and Keel by bench/frameworks/run.py.
source 'https://rubygems.org'

gem 'sidekiq', '8.1.7'
gem 'activesupport', '8.1.4'
gem 'actioncable', '8.1.4'
gem 'redis', '6.0.0'
