#!/usr/bin/env python3
"""Write .github/workflows/long-soak.yml: three arms, each a chain of segments.

The chain is one job per arm per segment, because a job that needs the one
before it is the only way GitHub Actions gates one arm without gating the
others: a matrix job would skip every arm's next segment when one arm fails.
That is twenty-seven near-identical stanzas, so they are generated, and
test_long_soak_workflow.py fails if the checked-in file drifts from this.
"""
from pathlib import Path

SEGMENTS = 9
SEGMENT_SECONDS = 19200  # 5h20m; nine of them are 48 hours
CYCLE_SECONDS = 30
# A pull request that touches the chain runs it in miniature: every handoff
# exercised, about an hour of wall clock, before the real thing depends on it.
REHEARSAL_SECONDS = 300
REHEARSAL_CYCLE_SECONDS = 20
ARMS = [
    ('p1', 'protocol 1, recovery', '--replication-protocol 1 --primary-crash-every 3'),
    ('p2c', 'protocol 2 concurrent, recovery', '--replication-protocol 2 --concurrent --primary-crash-every 3'),
    ('p2cc', 'protocol 2 concurrent, continuous primary', '--replication-protocol 2 --concurrent --primary-crash-every 0'),
]
WORKFLOW = Path(__file__).resolve().parent.parent / '.github' / 'workflows' / 'long-soak.yml'

HEADER = f'''name: Long soak

# Generated by scripts/generate-long-soak-workflow.py; edit that, not this.
#
# The 48-hour gate, met on free runners. A GitHub-hosted job ends at six hours,
# so the run is {SEGMENTS} segments of {SEGMENT_SECONDS // 3600}h{SEGMENT_SECONDS % 3600 // 60:02d}m, each handing the deployment to
# the next: both logs, the replica's checkpoint, and the harness's record of
# every value it was ever acknowledged, verified on the new machine before
# anything is written. Each arm is its own chain, so one arm's failure stops
# that arm and nothing else; a failed segment's successors are skipped.
#
# What this is: 48 hours of one dataset and one pair of logs under continuous
# writes, crash recovery and compaction, across {SEGMENTS - 1} planned restarts and
# {SEGMENTS} machines, on one binary. What it is not: 48 hours of process uptime. A
# leak that only shows past five hours of one process is invisible here; the
# growth bounds in soak.py are the check for that shape, applied every cycle.
# For true uptime, dispatch scheduled-soak.yml onto a self-hosted runner on a
# machine that can be kept for two days; see docs/long-run-gate.md.
#
# Every segment runs the binary built here once, so all {SEGMENTS * len(ARMS)} jobs validate
# the same bytes even if a Go patch release lands mid-run.
#
# A pull request that changes the chain, its segment or the harness runs the
# whole chain with {REHEARSAL_SECONDS // 60}-minute segments: every handoff, in about an hour.

on:
  pull_request:
    paths:
      - .github/workflows/long-soak.yml
      - .github/workflows/soak-segment.yml
      - scripts/soak.py
      - scripts/validation_lib.py
      - scripts/generate-long-soak-workflow.py
  workflow_dispatch:
    inputs:
      segment_seconds:
        description: Workload seconds per segment
        default: '{SEGMENT_SECONDS}'
      cycle_seconds:
        description: Seconds between crash/recovery cycles
        default: '{CYCLE_SECONDS}'
      runner:
        description: Runner label for the segments
        default: ubuntu-latest
  schedule:
    - cron: '0 4 * * 6'

permissions:
  contents: read

concurrency:
  group: long-soak-${{{{ github.ref }}}}
  cancel-in-progress: ${{{{ github.event_name == 'pull_request' }}}}

jobs:
  build:
    name: build once
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: |
          mkdir -p dist/long-soak
          go build -trimpath -o dist/long-soak/keel ./cmd/keel
          dist/long-soak/keel -version | tee dist/long-soak/version.txt
          sha256sum dist/long-soak/keel | tee dist/long-soak/keel.sha256
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: long-soak-binary
          path: dist/long-soak
          retention-days: 30
'''


def segment_job(arm, title, args, segment):
    needs = 'build' if segment == 1 else f'{arm}-s{segment - 1}'
    previous = '' if segment == 1 else f'long-soak-{arm}-s{segment - 1}'
    return f'''  {arm}-s{segment}:
    name: {title} {segment}/{SEGMENTS}
    needs: {needs}
    uses: ./.github/workflows/soak-segment.yml
    with:
      arm: {arm}
      args: {args}
      segment: {segment}
      segments: {SEGMENTS}
      previous: '{previous}'
      seconds: ${{{{ github.event_name == 'pull_request' && '{REHEARSAL_SECONDS}' || github.event.inputs.segment_seconds || '{SEGMENT_SECONDS}' }}}}
      cycle_seconds: ${{{{ github.event_name == 'pull_request' && '{REHEARSAL_CYCLE_SECONDS}' || github.event.inputs.cycle_seconds || '{CYCLE_SECONDS}' }}}}
      runner: ${{{{ github.event.inputs.runner || 'ubuntu-latest' }}}}
'''


def render():
    return HEADER + ''.join(segment_job(arm, title, args, segment)
                            for arm, title, args in ARMS
                            for segment in range(1, SEGMENTS + 1))


if __name__ == '__main__':
    WORKFLOW.write_text(render())
    print(WORKFLOW)
